.TH "C:/Users/Guillaume/Documents/GitHub/Projet_Elf/elfdeleterel.c" 3 "Fri Jan 15 2016" "Projet_Elf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Guillaume/Documents/GitHub/Projet_Elf/elfdeleterel.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'elfdeleterel\&.h'\fP
.br
\fC#include <string\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBdelRelTable\fP (char *filePath, Elf32_Ehdr header, Elf32_Shdr *shdr)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char* delRelTable (char * filePath, Elf32_Ehdr header, Elf32_Shdr * shdr)"

.PP
Definition at line 5 of file elfdeleterel\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Projet_Elf from the source code\&.
