.TH "C:/Users/Guillaume/Documents/GitHub/Projet_Elf/elfmodifsymb.h" 3 "Fri Jan 15 2016" "Projet_Elf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Guillaume/Documents/GitHub/Projet_Elf/elfmodifsymb.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <elf\&.h>\fP
.br
\fC#include 'filereader\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBelfmodifsymb\fP (char *filePath, Elf32_Ehdr header, Elf32_Ehdr headerOLD, Elf32_Shdr *shdr, Elf32_Shdr *shdrNEW, Elf32_Sym *sym)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char* elfmodifsymb (char * filePath, Elf32_Ehdr header, Elf32_Ehdr headerOLD, Elf32_Shdr * shdr, Elf32_Shdr * shdrNEW, Elf32_Sym * sym)"

.PP
Definition at line 3 of file elfmodifsymb\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Projet_Elf from the source code\&.
