.TH "C:/Users/Guillaume/Documents/GitHub/Projet_Elf/elfrelocateSymb.c" 3 "Fri Jan 15 2016" "Projet_Elf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Guillaume/Documents/GitHub/Projet_Elf/elfrelocateSymb.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'elfrelocateSymb\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBELF_RELOC_ERR\fP   \-1"
.br
.ti -1c
.RI "#define \fBDO_ARM_ABS32\fP(S,  A,  T)   (S + A) | T"
.br
.ti -1c
.RI "#define \fBDO_ARM_ABS16\fP(S,  A)   (S + A)"
.br
.ti -1c
.RI "#define \fBDO_ARM_ABS12\fP(S,  A)   (S + A)"
.br
.ti -1c
.RI "#define \fBDO_ARM_ABS8\fP(S,  A)   (S + A)"
.br
.ti -1c
.RI "#define \fBDO_ARM_CALL\fP(S,  A,  T,  P)   ((S + A) | T) \- P"
.br
.ti -1c
.RI "#define \fBDO_ARM_JUMP24\fP(S,  A,  T,  P)   ((S + A) | T) \- P"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBelfrelocatesymb\fP (char *filePath, Elf32_Ehdr header, Elf32_Ehdr headerNew, Elf32_Rel **rel, Elf32_Shdr *shdr, Elf32_Shdr *shdrNew, Elf32_Sym *symOLD, Elf32_Sym *sym)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DO_ARM_ABS12(S, A)   (S + A)"

.PP
Definition at line 5 of file elfrelocateSymb\&.c\&.
.SS "#define DO_ARM_ABS16(S, A)   (S + A)"

.PP
Definition at line 4 of file elfrelocateSymb\&.c\&.
.SS "#define DO_ARM_ABS32(S, A, T)   (S + A) | T"

.PP
Definition at line 3 of file elfrelocateSymb\&.c\&.
.SS "#define DO_ARM_ABS8(S, A)   (S + A)"

.PP
Definition at line 6 of file elfrelocateSymb\&.c\&.
.SS "#define DO_ARM_CALL(S, A, T, P)   ((S + A) | T) \- P"

.PP
Definition at line 7 of file elfrelocateSymb\&.c\&.
.SS "#define DO_ARM_JUMP24(S, A, T, P)   ((S + A) | T) \- P"

.PP
Definition at line 8 of file elfrelocateSymb\&.c\&.
.SS "#define ELF_RELOC_ERR   \-1"

.PP
Definition at line 2 of file elfrelocateSymb\&.c\&.
.SH "Function Documentation"
.PP 
.SS "char* elfrelocatesymb (char * filePath, Elf32_Ehdr header, Elf32_Ehdr headerNew, Elf32_Rel ** rel, Elf32_Shdr * shdr, Elf32_Shdr * shdrNew, Elf32_Sym * symOLD, Elf32_Sym * sym)"

.PP
Definition at line 10 of file elfrelocateSymb\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Projet_Elf from the source code\&.
