.TH "C:/Users/Guillaume/Documents/GitHub/Projet_Elf/etape2.c" 3 "Fri Jan 15 2016" "Projet_Elf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Guillaume/Documents/GitHub/Projet_Elf/etape2.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'etape2\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBread_elf_header\fP (int32_t fd, Elf32_Ehdr *elf_header)"
.br
.ti -1c
.RI "void \fBprint_elf_section_table\fP (Elf32_Ehdr elf_header, FILE *f)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void print_elf_section_table (Elf32_Ehdr elf_header, FILE * f)"

.PP
Definition at line 13 of file etape2\&.c\&.
.SS "void read_elf_header (int32_t fd, Elf32_Ehdr * elf_header)"

.PP
Definition at line 5 of file etape2\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Projet_Elf from the source code\&.
