.TH "C:/Users/Guillaume/Documents/GitHub/Projet_Elf/filereader.c" 3 "Fri Jan 15 2016" "Projet_Elf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Guillaume/Documents/GitHub/Projet_Elf/filereader.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'filereader\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBreadFileBytes\fP (const char *name)"
.br
.ti -1c
.RI "int \fBwriteFileBytes\fP (char *fileBytes, char *fileName, int size)"
.br
.ti -1c
.RI "int \fBis_big_endian\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int is_big_endian (void)"

.PP
Definition at line 32 of file filereader\&.c\&.
.SS "char* readFileBytes (const char * name)"

.PP
Definition at line 3 of file filereader\&.c\&.
.SS "int writeFileBytes (char * fileBytes, char * fileName, int size)"

.PP
Definition at line 15 of file filereader\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Projet_Elf from the source code\&.
