.TH "md__c_1__users__guillaume__documents__git_hub__projet__elf__r_e_a_d_m_e" 3 "Fri Jan 15 2016" "Projet_Elf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__c_1__users__guillaume__documents__git_hub__projet__elf__r_e_a_d_m_e \- Projet ELF 

.SS "Amédée Fleau - Clément Heresaz - Guillaume Chaput - Lucas Albarede -Loïc Chevalier"
.PP
## Installation 
.PP
.nf
1 make

.fi
.PP
.PP
## Suppression 
.PP
.nf
1 make clean

.fi
.PP
.PP
.SS "Utilisation"
.PP
### Flags: 
.PP
.nf
1 \&./main -f <FILENAME> <OPTS>

.fi
.PP
.PP
Options Effet  -f Filename (required) -h Header -S Sections -x<num> Detail Section <num> -s Symbol Table -r Relocation Table -d Delete REL (new file generated) 
.SS "TODO:"
.PP
.IP "\(bu" 2
Etape 7
.PP
.PP
.RS 4
Bonne année 2016
.RE
.PP

